version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: kikiodazie/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongoDB
      

  mongoDB:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=divine
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db 
  
  redis:
    image: redis


volumes:
  mongo-db: