version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongoDB
      

  mongoDB:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=divine
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db 


volumes:
  mongo-db: